### ISSUE TITLE
No sample VoiceAttack profile

### ISSUE THREAD

**Issue by Darkhand81** [InvalidCastEx/CommandLineMedia#1]
The documentation says that a sample VoiceAttack profile is included, but it is not in the release zip file or in the code.

Thanks!

**Comment by InvalidCastEx** [comment]
Sorry about that. I missed it in the migration. It's in the docs folder now.

[Right Click -> Save As...](https://raw.githubusercontent.com/InvalidCastEx/CommandLineMedia/master/docs/Sample%20Spotify%20Voice%20Attack%20Profile.vap)
